import { RequiredDataFromCollectionSlug } from 'payload'

export const contactForm: RequiredDataFromCollectionSlug<'forms'> = {
  confirmationMessage: {
    root: {
      type: 'root',
      children: [
        {
          type: 'heading',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Thanks. Your project enquiry has been received.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          tag: 'h2',
          version: 1,
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      version: 1,
    },
  },
  confirmationType: 'message',
  createdAt: '2023-01-12T21:47:41.374Z',
  emails: [
    {
      emailFrom: 'Vorteks Digital <info@vorteksdigital.co.za>',
      emailTo: 'info@vorteksdigital.co.za',
      replyTo: '{{work-email}}',
      message: {
        root: {
          type: 'root',
          children: [
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'A new project enquiry was submitted through the Vorteks Digital website.',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
      subject: 'New Vorteks Digital project enquiry',
    },
  ],
  fields: [
    {
      name: 'full-name',
      blockName: 'full-name',
      blockType: 'text',
      label: 'Your name',
      required: true,
      width: 100,
    },
    {
      name: 'work-email',
      blockName: 'work-email',
      blockType: 'email',
      label: 'Work email',
      required: true,
      width: 100,
    },
    {
      name: 'company',
      blockName: 'company',
      blockType: 'text',
      label: 'Company',
      required: false,
      width: 100,
    },
    {
      name: 'project-type',
      blockName: 'project-type',
      blockType: 'select',
      label: 'What do you need?',
      options: [
        { label: 'Website', value: 'website' },
        { label: 'Digital product', value: 'digital-product' },
        { label: 'Bespoke digital solution', value: 'bespoke-solution' },
        { label: 'Website maintenance', value: 'website-maintenance' },
        { label: 'Marketing or SEO support', value: 'marketing-seo' },
        { label: 'Brand or graphic design', value: 'brand-design' },
        { label: 'Not sure yet', value: 'not-sure' },
        { label: 'Something else', value: 'other' },
      ],
      required: true,
      width: 100,
    },
    {
      name: 'project-details',
      blockName: 'project-details',
      blockType: 'textarea',
      label: 'Project details',
      required: true,
      width: 100,
    },
  ],
  redirect: undefined,
  submitButtonLabel: 'Send project enquiry',
  title: 'Project Enquiry',
  updatedAt: '2023-01-12T21:47:41.374Z',
}
